### ISSUE TITLE
Reference lines using logscale

### ISSUE THREAD

**Issue by toffis81** [gforge/forestplot#10]
[library.txt](https://github.com/gforge/forestplot/files/995600/library.txt)
In the code attached we are trying to add references lines to, say, 0.1 and 10. We use the following:

`grid = structure(c(10^-1, 10^1), gp = gpar(col = "steelblue", lty=2)),`

However, the lines are not appearing where we expect them to be (they seem to follow some sort of implicit linear scale). We have tried to use negative numbers  then the exponential function (as suggested by the error message) but we cannot quite get the placement of the lines where we’d like them. Also, all the lines seem to be to the right of the default ‘zero’ line and we cannot place anything to the left of it.
 
The problem does not seem to be present when the logscale is not used. Could this be a bug?

**Comment by gforge** [comment]
Thanks for the report. Can you check that the bug is fixed in the dev-branch?

**Comment by toffis81** [comment]
Hi there,
Thanks for the quick turnaround - this is now working perfectly.
![image](https://cloud.githubusercontent.com/assets/28646749/26150508/8b2971ec-3af6-11e7-9b99-07cb946e2648.png)
