### ISSUE TITLE
Text/Label & Title Positions

### ISSUE THREAD

**Issue by toffis81** [gforge/forestplot#11]
Apologies in advance if this should be two separate issues.

Would it be possible to add a method to position the title centrally over wherever the plot is displayed? Here a couple of examples I have produced but, at the moment, the text directly over the plot is hard coded (position-wise) using grid.text:
![image](https://cloud.githubusercontent.com/assets/28646749/26151596/6e642872-3afb-11e7-886a-b859c0d66f0f.png)
And also:
![image](https://cloud.githubusercontent.com/assets/28646749/26151414/b3f78704-3afa-11e7-973a-80230c215679.png)

Similarly, would it be possible to add a way to label the bottom axis? Here is another forest plot (from a previous issue I have raised) but I am have to hard code the positions of both bits of text (Favour X and Favours Y):
![image](https://cloud.githubusercontent.com/assets/28646749/26151719/e8568df0-3afb-11e7-8286-b68504b3c18a.png)

Please let me know if you need anything further from me.

**Comment by gforge** [comment]
Sure, this is possible but I may have to put it on ice for now as I don't have the time if you want to tinker then the title is create [here](https://github.com/gforge/forestplot/blob/master/R/forestplot.R#L556-L558) - you need to pride the new center positions.

The text options would probably be easiest to add [here](https://github.com/gforge/forestplot/blob/master/R/forestplot.R#L517-L534). Shouldn't be that difficult.

**Comment by toffis81** [comment]
I'll be happy to help out with this but I must confess I am very new to package development/making updates.

I tried looking at the part of the code where the title is created but it seems to reference an internally defined function `prGridPlotTitle` (unless I am missing something?).

If someone could nudge me in the right direction I'd be happy to try to make this tweak. Same goes for Issue #12.

**Comment by gforge** [comment]
Neat. I try encapsulate as much as I can into functions that I call "private" as they aren't exported into the general namespace (they're available usin ::: e.g. forestplot:::prGridPlotTitle). They should all be located in the [R/private.R](https://github.com/gforge/forestplot/blob/master/R/private.R) file.

Fixing up someone else's package is an excellent learning exercise and good way to start before making your own package. It's also greatly appreciated :-)

Do the following (some details may be off but this is the gist of it):
1. Install [Git](https://git-scm.com/) on your computer + install the R package devtools
2. Fork the package into your own user
3. Clone the package (use RStudio, create a new project and choose existing Git repo)
4. Try the changes your interested in and in R studio you can directly load them by pressing "Ctrl+L"
5. Once you're happy you commit your changes (you can do this in RStudio's top right window)
6. Push the changes to Github (just press push)
7. Log onto your Github account, go into your Fork of the package and do a "Pull Request"

Thanks!

**Comment by gforge** [comment]
Fixed in version 3.0
