### ISSUE TITLE
Plot border

### ISSUE THREAD

**Issue by toffis81** [gforge/forestplot#12]
Please would it be possible include an option to draw a border around plot please? Something like the following:
![image](https://cloud.githubusercontent.com/assets/28646749/26151876/93ec0c08-3afc-11e7-988e-ee5a0324f7f7.png)
Thanks again!

**Comment by gforge** [comment]
Sure, you just need to have do a grid.rect() before drawing the content.

**Comment by gforge** [comment]
Solved in 3.0
