### ISSUE TITLE
Keep getting error message...

### ISSUE THREAD

**Issue by Siromujin** [gforge/forestplot#15]
Hi, I keep getting the following message when I try to run the script. When I run it with data with 7 rows it ran fine. I am trying to run it with a dataset with 38 rows now. 

Thank you!

Error in if (any(textHeight * (nr + 0.5) * 1.5 < info)) info <- textHeight *  : 
  missing value where TRUE/FALSE needed

**Comment by gforge** [comment]
It may be that your plot is bigger than the screen, do you have a reproducible example?

**Comment by Siromujin** [comment]
Hi. The issue resolved when I manually entered the boxsize to be the relative weight. I do have a new issue though . In the new plot I created (with >100) rows, the texts are all overlapping. I managed to separate them by making the font very small but when I exported the file as image, they came out pretty blurry. Is there a way where I can produce a high resolution forest plot? 

Thank you again for your help!

**Comment by gforge** [comment]
Checkout the device options, this is not a bug.
