### ISSUE TITLE
forestplot function crashes when there are NA row and maybe too many rows in the data

### ISSUE THREAD

**Issue by teemacatac** [gforge/forestplot#19]
I have a data frame of mean, lower and upper, first row is NA's and there are 57 rows. Corresponding label text has 57 rows, and first row is col title. When I run the function it gave this error msg below. When subset to the first 35 rows, it runs OK. When removing the NA rows, it runs OK. 

Error in if (any(textHeight * (nr + 0.5) * 1.5 < info)) info <- textHeight *  : 
  missing value where TRUE/FALSE needed

**Comment by gforge** [comment]
Do you have a reproducible example?

**Comment by teemacatac** [comment]
the problem seems to go away, will reach out if running into it again.

On 5/2/18, Max Gordon <notifications@github.com> wrote:
> Do you have a reproducible example?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/gforge/forestplot/issues/19#issuecomment-386191060


-- 
Best regards

Yafeng

**Comment by gforge** [comment]
Ok, make sure to have a reproducible example and that you're running the last version.
