### ISSUE TITLE
fn.ci_norm applies shapes to wrong markers

### ISSUE THREAD

**Issue by proshano** [gforge/forestplot#2]
Not a bug, thank you

(content removed because relevant to upcoming publication)

```
```

**Comment by gforge** [comment]
This is sort of a bug. As the input matrix is 3 x 3 it chooses of the functions should be applied to rows of columns. The choice is obviously different for colors and CI functions. 

In order to get your desired plot just provide a 3 x 3 matrix för the function argument

**Comment by gforge** [comment]
In the 1.5 version this behavior is now consistent. Thanks for the hint.

**Comment by proshano** [comment]
That's incredible thank you!

I wanted to ask - is it possible to put text on the left beside each
estimate when you shoe several estimates like that? I'd like to put the
relative risk and confidence intervals specific to each branch of the
forest plot.

Pavel
