### ISSUE TITLE
Problems when Installing forestplot from R Studio, newest version

### ISSUE THREAD

**Issue by SoMaGe** [gforge/forestplot#21]
Dear all, 
when installing forestplot from R Studio I get the following error message (

* installing *source* package 'forestplot' ... 
** Paket 'forestplot' erfolgreich entpackt und MD5 Summen überprüft 
** R 
** data 
** inst 
** preparing package for lazy loading 
Warnung: package 'magrittr' was built under R version 3.2.5 Warnung: package 'checkmate' was built under R version 3.2.5 Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :    there is no package called 'backports' Error : package 'checkmate' could not be loaded ERROR: lazy loading failed for package 'forestplot' * removing 'C:/Users/SGeiger_Admin/Documents/R/win-library/3.2/forestplot' Warning in install.packages :   running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\SGeiger_Admin\Documents\R\win-library\3.2" "C:/Users/SGeiger_Admin/Documents/R/win-library/3.2/forestplot/forestplot_1.7.2.tar.gz"' had status 1 Warning in install.packages :   installation of package ‘C:/Users/SGeiger_Admin/Documents/R/win-library/3.2/forestplot/forestplot_1.7.2.tar.gz’ had non-zero exit status > library(forestplot) Error in library(forestplot) : es gibt kein Paket namens ‘forestplot’
--
 
> | >
>

**Comment by gforge** [comment]
Sorry but this seems to be a environment issue with your installation and not a package issue.
