### ISSUE TITLE
graph.pos when labeltext is as a list

### ISSUE THREAD

**Issue by th-zelniker** [gforge/forestplot#24]
Sorry to bother you again. :-) I absolutely love this package but when using a list for labeltext (e.g., because of expressions such as a greater equal sign), it is not possible to modify the graph position as flexible when labeltext is a matrix. This is very well described in the help function but is there any way to modify that? What would be the best way to tackle that?  

I was already thinking of combining two plots (1 without a graph and a 2nd with graph)  using 

grid.newpage()
pushViewport(viewport(layout = grid.layout(1, 2,.. etc. 

but I get an error message when I do not inlcude mean, lower and upper.

**Comment by gforge** [comment]
Thanks.

It was a while since I wrote this package. If you want to manually change the widths you need to somehow target this row: https://github.com/gforge/forestplot/blob/master/R/forestplot.R#L510

**Comment by gforge** [comment]
In 3.0 combining plots is much easier and less error prone. You have also more control over the text style. The graph width should also hopefully work better.
