### ISSUE TITLE
Use different color in every row

### ISSUE THREAD

**Issue by ghost** [gforge/forestplot#25]
In the forestplot.pdf, I saw this:"If you have several values per row in a forestplot you can set a color to a vector where the first value represents the first line/box, second the second line/box etc."

I wanted to use different colors to display my 4 values, and I set this:

**col = fpColors(lines=c('red','blue','black','grey'), box=c('red','blue','black','grey'), zero = "black")**

But all the values' color turn to red, rather than the first row in red, the second in blue etc. I don't know why..

Your help is highly appreciated.

**Comment by gforge** [comment]
Could you post a full test?

**Comment by ghost** [comment]
Of course yes, This is my code and my data.
[
[code_and_data.zip](https://github.com/gforge/forestplot/files/2948368/code_and_data.zip)
](url)

**Comment by gforge** [comment]
Could you post an example without zip?

**Comment by gforge** [comment]
See this question:
https://stackoverflow.com/questions/39392706/using-the-r-forestplot-package-is-there-a-way-to-assign-variable-colors-to-boxe/40057330?noredirect=1#comment97042779_40057330
