### ISSUE TITLE
Combining forest plots 

### ISSUE THREAD

**Issue by MaVdb** [gforge/forestplot#29]
I would like to combine 2 plots, 1 row with panels (2 separate forest plots) and add panel labels (letters a & b)

Is there an option similar to grid.arrange/par(mfrow=c(1,2)) that can be used?

par(mfrow=c(1,2)) seems not to work

**Comment by gforge** [comment]
You need to use the raw grid package with viewport and grid.layout, I think I added it to the vignette in the last update
