### ISSUE TITLE
fpShapesGp from vignette does not exist

### ISSUE THREAD

**Issue by annaoj2** [gforge/forestplot#35]
Example from vignette: 

> library(forestplot)
Loading required package: grid
Loading required package: magrittr
Loading required package: checkmate
> ask <- par(ask = TRUE)
> # An example of how fpShapesGp works
> styles <- fpShapesGp(
+     default = gpar(col = "pink", lwd = 2, lineend = "square", linejoin = "mitre"),
+     grid = list(
+         gpar(col = "blue"),
+         gpar(col = "black"),
+         gpar(col = "blue")
+     ),
+     box = list(
+         gpar(fill = "black"),
+         gpar(fill = "blue"),
+         gpar(fill = "black"),
+         gpar(fill = "blue")
+     ),
+     lines = gpar(lty = "dashed"),
+     vertices = gpar(lwd = 5, col = "red")
+ )
Error in fpShapesGp(default = gpar(col = "pink", lwd = 2, lineend = "square",  : 
  could not find function "fpShapesGp"

R version 3.6.3 (2020-02-29)
forestplot_1.9
![no_fpshapesgp](https://user-images.githubusercontent.com/2489617/92961573-4e6d3000-f424-11ea-9142-c4c8750b39c2.png)

**Comment by gforge** [comment]
The current version of forestplot is 1.10, have you tried upgrading?

**Comment by annaoj2** [comment]
Oh, I'm so sorry! I had already updated it but it didn't work properly - now that I uninstalled and reinstalled, it is there. Sorry about that.
