### ISSUE TITLE
zero line not showing after recent update (10 Aug 2021)

### ISSUE THREAD

**Issue by eliasallara** [gforge/forestplot#42]
Hello, 

Thank you for this amazing package! It's working fine after the latest update, except for one thing I'm unable to fix - the zero line, which previously was working, does not show anymore.

I tried to use the default settings and to play around with settings (e.g. `fpColors(zero="black")`, `zero=1`, `zero=0`). Nothing seems to have an impact.

Do you have any suggestions? Happy to provide further info & a reproducible example if useful.

**Comment by gforge** [comment]
Yeah, this seems to be an issue due to that `lwd.zero` isn't set to a default value, I have started to work on a fix here: https://github.com/gforge/forestplot/tree/zero-effect_bug

Should we always have a zero line or only when requested?

**Comment by eliasallara** [comment]
That's great, thanks! 

I personally don't mind either option - the documentation is excellent so I have no problem switching the zero line on or off. 

A lot of people use the package though, and they might expect it to behave like in the previous versions (or otherwise they'll have to update their code). So probably the zero line should be included by default? Unless, of course, you've had several requests of users asking to disable it...

**Comment by gforge** [comment]
Yeah, could you check the updated branch and see if it behaves as you expect?

**Comment by eliasallara** [comment]
It works - thank you!

**Comment by gforge** [comment]
Fixed in 2.0.1 which is submitted to CRAN
