### ISSUE TITLE
Multiple bands per variable - some NA

### ISSUE THREAD

**Issue by sel9828** [gforge/forestplot#5]
Hello, 

I would like to plot multiple bands per variable, but for some variables I do not have all bands available. E.g., in the online example, imagine if one of the variables, e.g., Charlsons High:Low, did not have data for e.g., Sweden. If I attempt to plot using an NA for the elements where Sweden's data should go, then nothing gets plotted for the variable Charlsons High:Low, not even Denmark's bands. I "solved" this by just inputting the data as "0"s and making the box size 0 so that the bands wouldn't show up in places where I did not have data, but it would be nice if the package could recognize NA as unavailable data and still plot other data for that variable. 

Thank you

**Comment by gforge** [comment]
Good suggestion. NA's have been intended for empty rows and not really missing observations but I can see the utility in it. Will see when I can add this.

**Comment by sel9828** [comment]
Thank you!

**Comment by gforge** [comment]
Added to the dev-branch
