### ISSUE TITLE
Can't install in older version of R less than 4.1

### ISSUE THREAD

**Issue by sclewis23** [gforge/forestplot#51]
It seems the R base pipeOp was introduced in the latest version of forestplot, but the R base pipeOp is not available in older version of R.
I'm using R3.6.3 and R4.0.2
R base pipeOp |>

**Comment by gforge** [comment]
You will need to either install an old package version or upgrade R

**Comment by sclewis23** [comment]
Why not update your are version dependency?

Depends:
    R (>= 4.1.0),

**Comment by gforge** [comment]
Sure, I'll add that in 3.0.1
