### ISSUE TITLE
Grid lines not showing

### ISSUE THREAD

**Issue by MartinNygaardJohansen** [gforge/forestplot#55]
I am struggling to show vertical reference lines in my forest plot.
In the very last example in the vignette (as of 2022-10-09), it is shown how to modify grid lines: "You can easily customize both what grid lines to use and what type they should be by adding the gpar object to a vector". However, in the plot that is generated by the example there are no grid lines at the expected positions.
Also, I am somewhat confused about the syntax, since there now seems to be an argument "grid" in the fp_set_style to provide a gpar for the grid, but the aforementioned example shows a different way to provide the gpar directly in the "grid" argument of "forestplot".

Any help or explanation would be highly appreciated.

**Comment by MartinNygaardJohansen** [comment]
I just realized that this was fixed in Version 3.1.1

**Comment by gforge** [comment]
Yeah, I accidentally broke some stuff in version 3, 3.1.1 seems to work fine through all the examples but there are a lot of use cases to be tested...
