### ISSUE TITLE
Error when the value equals to the lower or upper

### ISSUE THREAD

**Issue by Kiven668** [gforge/forestplot#56]
Hi All,

I am trying to draw a forest plot with below data. It returns error, how can I handle this? Thank you
```
Error in prFpConvertMultidimArray(mean) : 
  Sorry did not manage to correctly identify the upper/lower boundaries from the input matrix.
```
mean       lower        upper
1.10 	0.98 	1.20 
1.10 	1.00 	1.10 
1.10 	1.01 	1.10

**Comment by gforge** [comment]
I suggest you use the new tidyverse inspired syntax
