### ISSUE TITLE
Cannot install forest plot with R 4.3.2

### ISSUE THREAD

**Issue by yatnayatna** [gforge/forestplot#63]
I am Trying to install forestplot on Rstudio and am getting:  package ‘https://cran.r-project.org/web/packages/forestplot/index.html’ is not available for this version of R
install.packages("https://cran.r-project.org/web/packages/forestplot/index.html")
I tried from tarball too, 
install.packages("~/Downloads/forestplot_3.1.3.tgz", repos = NULL, type = .Platform$pkgType)

**Comment by gforge** [comment]
This is not a package issue.
