### ISSUE TITLE
xlog error in R 4.3

### ISSUE THREAD

**Issue by VenusSo** [gforge/forestplot#67]
The setting `xlog=TRUE, zero=1` has been working well until R 4.3 (it could also be some environment changes due to our R 4.3 upgrade).  The symptom is the `xticks` (e.g. c(0.5, 1, 2)) values are interpreted as log values and are exponentiated to create the X-axis tick labels. Please see screenshot: 
![image](https://github.com/user-attachments/assets/720df53a-9ec4-4702-b0e4-ed56c129fae4)

**Comment by gforge** [comment]
Thanks, could you check that it works, `devtools::install_github("gforge/forestplot", ref = "develop")`?

**Comment by VenusSo** [comment]
@gforge Yes, it's fixed!  Thanks!
