### ISSUE TITLE
Error in prFpConvertMultidimArray(mean)

### ISSUE THREAD

**Issue by jacsouzalima** [gforge/forestplot#9]
I'm attempting to create a forest plot with the following code, but it isn't working:
I keep getting the same error message:

"Error in prFpConvertMultidimArray(mean) : 
  Sorry did not manage to automatically identify the upper/lower boundaries."

Any help would be much appreciated!

cochrane_from_rmeta <- 
  structure(list(
    mean  = c(NA, NA, -0.6098, -0.0805, -0.0715, -0.0445, NA, -0.067), 
    lower = c(NA, NA, -2.8806, -0.1488,-0.1673, -0.1250, NA, -0.1128),
    upper = c(NA, NA, 1.6611, -0.0122, 0.0244, 0.0359, NA, -0.0213)),
    .Names = c("mean", "lower", "upper"), 
    row.names = c(NA, -11L), 
    class = "data.frame")
tabletext<-cbind(
  c("", "Genetic parameter", "Allelic richness", "fis", 
    "Fst", "He", NA, "Random effects model"),
  c("Megafauna", NA, "12", "26", 
    "15", "28", NA, NA),
  c("No megafauna", NA, "53", "68", 
    "47", "76", NA, NA),
  c("", "MD", "-0.61", "-0.08", 
    "-0.07", "-0.04", NA, "-0.07"))
forestplot(tabletext, 
           cochrane_from_rmeta,new_page = TRUE,
           is.summary=c(TRUE,TRUE,rep(FALSE,8),TRUE),
           clip=c(-2.5,2.5), 
           xlog=TRUE, 
           col=fpColors(box="royalblue",line="darkblue", summary="royalblue"))

**Comment by gforge** [comment]
Your data frame seems corrupted. There are eight elements but you state 11 rows - there is something strange there. There is also a mismatch between the data and the text, that has the correct 8 rows. 

```
cochrane_from_rmeta <-
  structure(list(
    mean = c(NA, NA, -0.6098, -0.0805, -0.0715, -0.0445, NA, -0.067),
    lower = c(NA, NA, -2.8806, -0.1488,-0.1673, -0.1250, NA, -0.1128),
    upper = c(NA, NA, 1.6611, -0.0122, 0.0244, 0.0359, NA, -0.0213)),
    .Names = c("mean", "lower", "upper"),
    row.names = c(1:8),
    class = "data.frame")
tabletext<-cbind(
  c("", "Genetic parameter", "Allelic richness", "fis",
    "Fst", "He", NA, "Random effects model"),
  c("Megafauna", NA, "12", "26",
    "15", "28", NA, NA),
  c("No megafauna", NA, "53", "68",
    "47", "76", NA, NA),
  c("", "MD", "-0.61", "-0.08",
    "-0.07", "-0.04", NA, "-0.07"))
forestplot(tabletext, 
           cochrane_from_rmeta,
           col=fpColors(box="royalblue",line="darkblue", summary="royalblue"))
```

**Comment by jacsouzalima** [comment]
Thanks a lot for help!
